### ISSUE TITLE
Can't download the japanese model?

### ISSUE THREAD

**Issue by ym1234** [tchayintr/latte-ptm-ws#1]
https://huggingface.co/yacht/latte-mc-bert-base-japanese-ws returns 404

**Comment by tchayintr** [comment]
@ym1234 Thanks for your interest in our work.

[https://huggingface.co/yacht/latte-mc-bert-base-japanese-ws](https://huggingface.co/yacht/latte-mc-bert-base-japanese-ws) was pre-trained with multiple Japanese datasets, including BCCWJ, Kyoto University Text Corpus, etc. Due to the license agreements, we are unable to upload this Japanese pre-trained model to Hugging Face.

I suggest you obtain the BCCWJ corpus and the Kyoto University Text Corpus, among others, and use our script to pre-train a model. I can also guide you through the pre-training steps if you manage to obtain these corpora

Sorry for the inconvenient.
